name: sats
description: Sovereign Bitcoin Scripting Wallet
version: 0.0.9
publish_to: none
platforms:
  android:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  animations: ^2.0.0
  bitcoin:
    path: packages/bitcoin
  bloc_concurrency: ^0.2.0
  # connectivity: ^3.0.3
  dio: ^4.0.5
  drag_and_drop_lists: ^0.3.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1
  # flutter_blue: ^0.8.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^3.0.6
  google_fonts: ^2.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  # local_auth: ^1.1.8
  oktoast: ^3.1.5
  open_mail_app: ^0.4.5
  path_provider: ^2.0.1
  pattern_formatter: ^2.0.0
  petitparser: ^5.0.0
  qr_flutter: ^4.0.0
  retry: ^3.1.0
  share: ^2.0.1
  stream_transform: ^2.0.0
  url_launcher: ^6.0.3
  utopic_tor_onion_proxy: ^0.4.0
  wasm: ^0.1.0+1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator:
    git:
      url: https://github.com/hivedb/hive.git
      ref: master
      path: hive_generator
  json_serializable: ^6.1.5
  lint: ^1.7.2
  mocktail: ^0.3.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fontawesome-webfont.ttf
  assets:
    - assets/icon/sm92.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/sm92.png"
