name: sats
description: Self-Sovereign Bitcoin Wallet
version: 0.0.18
publish_to: none
platforms:
  android:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  animations: ^2.0.0
  bloc_concurrency: ^0.2.0
  crypto: ^3.0.2
  # connectivity: ^3.0.3
  dio: ^4.0.5
  drag_and_drop_lists: ^0.3.2
  equatable: ^2.0.3
  file_cryptor: ^0.0.3
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_chat_ui: ^1.6.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_socks_proxy: ^0.0.2
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^3.0.6
  google_fonts: ^2.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  libstackmate:
    path: packages/libstackmate
  numeric_keyboard: ^1.1.0
  oktoast: ^3.1.5
  open_filex: ^3.4.0
  open_mail_app: ^0.4.5
  path: ^1.8.1
  path_provider: ^2.0.1
  pattern_formatter: ^2.0.0
  permission_handler: ^10.0.0
  petitparser: ^5.0.0
  qr_flutter: ^4.0.0
  share: ^2.0.1
  sqflite: ^2.0.3
  top_snackbar_flutter: ^2.1.1
  url_launcher: ^6.0.3
  utopic_tor_onion_proxy: ^0.4.0
  uuid: ^3.0.6
  wasm: ^0.1.0+1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator:
    git:
      url: https://github.com/hivedb/hive.git
      ref: master
      path: hive_generator
  json_serializable: ^6.1.5
  lint: ^1.7.2
  mocktail: ^0.3.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/sm92.png
    - assets/icon/bitcoin_icons/png/outline/node.png
    - assets/icon/bitcoin_icons/png/outline/home.png
    - assets/icon/bitcoin_icons/png/outline/ellipsis.png
    - assets/icon/bitcoin_icons/png/outline/satoshi-v2.png
    - assets/icon/bitcoin_icons/png/outline/proxy.png
    - assets/icon/bitcoin_icons/png/outline/link.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/sm92.png"
